const employees = [
  {
    id: 1,
    email: "employee1@gmail.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Create Login Page",
        taskDescription: "Build a responsive login page for the application.",
        taskDate: "2026-09-23",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Fix Navbar Bug",
        taskDescription:
          "Fix the navigation menu not working on mobile devices.",
        taskDate: "2026-09-24",
        category: "Bug Fix",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Update User Profile",
        taskDescription: "Add profile editing functionality for users.",
        taskDate: "2026-09-20",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Database Backup",
        taskDescription: "Create a backup of the application database.",
        taskDate: "2026-09-18",
        category: "Database",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Write API Documentation",
        taskDescription: "Document all available API endpoints.",
        taskDate: "2026-09-25",
        category: "Documentation",
      },
    ],
  },

  {
    id: 2,
    email: "employee2@gmail.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Design Dashboard",
        taskDescription: "Create a clean and responsive admin dashboard.",
        taskDate: "2026-09-23",
        category: "Design",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Create User API",
        taskDescription: "Develop API endpoints for managing users.",
        taskDate: "2026-09-24",
        category: "Backend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Setup Project",
        taskDescription:
          "Initialize the project and install required dependencies.",
        taskDate: "2026-09-19",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Test Authentication",
        taskDescription: "Test login and authentication functionality.",
        taskDate: "2026-09-25",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Update Dependencies",
        taskDescription: "Update outdated project dependencies.",
        taskDate: "2026-09-21",
        category: "Maintenance",
      },
    ],
  },

  {
    id: 3,
    email: "employee3@gmail.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Build Registration Form",
        taskDescription: "Create a registration form with validation.",
        taskDate: "2026-09-23",
        category: "Frontend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Implement Form Validation",
        taskDescription: "Add validation for all registration fields.",
        taskDate: "2026-09-24",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Create Contact Page",
        taskDescription: "Create a contact page with a working form.",
        taskDate: "2026-09-20",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Deploy Application",
        taskDescription: "Deploy the latest version of the application.",
        taskDate: "2026-09-17",
        category: "Deployment",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Optimize Website",
        taskDescription: "Improve website loading speed and performance.",
        taskDate: "2026-09-26",
        category: "Performance",
      },
    ],
  },

  {
    id: 4,
    email: "employee4@gmail.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Create Product Page",
        taskDescription: "Build a responsive product details page.",
        taskDate: "2026-09-23",
        category: "Frontend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Add Search Feature",
        taskDescription: "Add search functionality to the product list.",
        taskDate: "2026-09-24",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Fix CSS Issues",
        taskDescription: "Fix layout and responsive design issues.",
        taskDate: "2026-09-20",
        category: "Bug Fix",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Connect Product API",
        taskDescription: "Connect the frontend product page with the API.",
        taskDate: "2026-09-25",
        category: "Backend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Write Test Cases",
        taskDescription: "Write test cases for the product functionality.",
        taskDate: "2026-09-21",
        category: "Testing",
      },
    ],
  },

  {
    id: 5,
    email: "employee5@gmail.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Create Reports",
        taskDescription: "Create monthly reports for the admin.",
        taskDate: "2026-09-23",
        category: "Reports",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Update Dashboard",
        taskDescription: "Add new statistics to the dashboard.",
        taskDate: "2026-09-24",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Review User Data",
        taskDescription: "Review and verify existing user information.",
        taskDate: "2026-09-20",
        category: "Management",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Fix Report Error",
        taskDescription: "Fix incorrect data appearing in the reports.",
        taskDate: "2026-09-18",
        category: "Bug Fix",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Prepare Presentation",
        taskDescription: "Prepare the project progress presentation.",
        taskDate: "2026-09-26",
        category: "Presentation",
      },
    ],
  },
];

const admin = [
  {
    id: 6,
    email: "admin@gmail.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
